name: LD40
description: LUDUM DAAAAARE!
version: 0.0.1
author: TTFTCUTS

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  GameLib2:
    git: git://github.com/TTFTCUTS/GameLib2.git

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- $dart2js:
    sourceMaps: true
    commandLineOptions: [--fast-startup, --trust-type-annotations]
    $exclude: ["web/manifest/bundlebuilder.dart", "web/manifest/sourcemanifest.txt"]


